### ISSUE TITLE
resource help info doesn't correctly show "ports"

### ISSUE THREAD

**Issue by djosborne** [projectcalico/libcalico-go#137]
Ports needs to be a list, but the docs show them as comma separated string

**Comment by robbrockbank** [comment]
@djosborne 

I think this might have been fixed as a side effect of my PR that beefed up the docs.  Can you check and close this out if that;s the case.

**Comment by djosborne** [comment]
Still incorrect here: https://github.com/tigera/libcalico-go/blob/master/docs/calicoctl/resources/policy.md#sample-yaml
